# https://wiki.squid-cache.org/ConfigExamples/ContentAdaptation/C-ICAP

PidFile /run/c-icap/c-icap.pid
CommandsSocket /run/c-icap/c-icap.ctl

Port 1344

ServerLog /dev/stdout
AccessLog /dev/stdout

Service squidclamav squidclamav.so
